### ISSUE TITLE
Maximum Stack Size Exceeded

### ISSUE THREAD

**Issue by sdp1019** [florentbr/SeleniumBasic#77]
Hi!

Thank you for all of the work you have done, I really appreciate your time and effort!

The current code I have works fine until it hits the driver.openWindow line, where it actually succeeds in opening the new window, but throws the maximum call stack size error shown below.

Can you help me diagnose this? (I have listed code below)

**Error Message:**
System.InvalidOperationException: unknown error: Maximum call stack size exceeded
  (Session info: chrome=48.0.2564.109)
  (Driver info: chromedriver=2.8.241075,platform=Windows NT 6.1 SP1 x86_64)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse) in c:\Projects\WebDriver\trunk\dotnet\src\webdriver\Remote\RemoteWebDriver.cs:line 1012
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) in c:\Projects\WebDriver\trunk\dotnet\src\webdriver\Remote\RemoteWebDriver.cs:line 846
   at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScriptInternal(String script, Boolean async, Object[] args) in c:\Projects\WebDriver\trunk\dotnet\src\webdriver\Remote\RemoteWebDriver.cs:line 1087
   at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScript(String script, Object[] args) in c:\Projects\WebDriver\trunk\dotnet\src\webdriver\Remote\RemoteWebDriver.cs:line 426
   at Selenium.Internal.SeleniumEmulation.GetEval.HandleSeleneseCommand(IWebDriver driver, String locator, String value) in c:\Projects\WebDriver\trunk\dotnet\src\webdriverbackedselenium\Internal\SeleniumEmulation\GetEval.cs:line 37
   at Selenium.Internal.SeleniumEmulation.SeleneseCommand.Apply(IWebDriver driver, String[] args) in c:\Projects\WebDriver\trunk\dotnet\src\webdriverbackedselenium\Internal\SeleniumEmulation\SeleneseCommand.cs:line 27
   at Selenium.Internal.SeleniumEmulation.OpenWindow.HandleSeleneseCommand(IWebDriver driver, String locator, String value) in c:\Projects\WebDriver\trunk\dotnet\src\webdriverbackedselenium\Internal\SeleniumEmulation\OpenWindow.cs:line 36
   at Selenium.Internal.SeleniumEmulation.SeleneseCommand.Apply(IWebDriver driver, String[] args) in c:\Projects\WebDriver\trunk\dotnet\src\webdriverbackedselenium\Internal\SeleniumEmulation\SeleneseCommand.cs:line 30
   at Selenium.Internal.CommandTimer.RunCommand() in c:\Projects\WebDriver\trunk\dotnet\src\webdriverbackedselenium\Internal\CommandTimer.cs:line 74
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Code:**

`Sub NoCoDiagnostic()
'
' NoCoDiagnostic Macro
'

Dim i As Integer
Dim driver As New SeleniumWrapper.WebDriver

Set keys = CreateObject("SeleniumWrapper.Keys")

driver.AddArgument "--disable-popup-blocking"

   i = 0
   
    driver.Start "chrome", ("https://simcontrolcenter.wireless.att.com/provision/ui/terminals/sims/sims.html")
    driver.Open ("https://simcontrolcenter.wireless.att.com/provision/ui/terminals/sims/sims.html")
    driver.Type "name=j_username", ("spalmer")
    driver.Type "name=j_password", ("ticktock")
    driver.clickAndWait ("xpath=//input[@type='submit']")
        
    For i = 1 To 3
            
            
            driver.Open ("https://simcontrolcenter.wireless.att.com/provision/ui/terminals/sims/sims.html")
            driver.Type "name=oneBox", (Worksheets("Sheet1").Cells(i + 1, 2).Value)
            driver.clickAndWait ("id=button-1103")
            driver.openWindow "https://simcontrolcenter.wireless.att.com/provision/ui/terminals/sims/sims.html", "i"
            
            
            
        
        i = i + 1
    Next i

'
End Sub
`

**Comment by florentbr** [comment]
You code is from SeleniumWrapper which is deprecated and no longer supported.
SeleniumBasic is the successor (https://github.com/florentbr/SeleniumBasic/releases).
With your example:
```vb
Dim driver As New Selenium.ChromeDriver, Keys As New Selenium.Keys
driver.Get "https://simcontrolcenter.wireless.att.com/provision/ui/terminals/sims/sims.html"
driver.FindElementByName("j_username").SendKeys "spalmer"
driver.FindElementByName("j_password").SendKeys "ticktock"
driver.FindElementByXPath("//input[@type='submit']").Submit

For i = 1 To 3
  driver.Get "https://simcontrolcenter.wireless.att.com/provision/ui/terminals/sims/sims.html"
  driver.FindElementByName("oneBox").SendKeys [Sheet1].Cells(i + 1, 2).Value
  driver.FindElementById("button-1103").Click Keys.Control
Next
```

**Comment by sdp1019** [comment]
Thank you for your assistance! I have editted the code and it is working again. My only question now is how do I do the equivalent of driver.openWindow?
